# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from soccer_msgs/dilemma.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class dilemma(genpy.Message):
  _md5sum = "b49206df1ee4999adb483454e619902e"
  _type = "soccer_msgs/dilemma"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool enableDilemma
uint8 UNKNOWN_TYPE=0
uint8 BENCH_OR_CENTER=1
uint8 BENCH_OR_GOAL=2
uint8 BENCH_OR_FAR=3
uint8 dilemmaType
time setDilemmaTime"""
  # Pseudo-constants
  UNKNOWN_TYPE = 0
  BENCH_OR_CENTER = 1
  BENCH_OR_GOAL = 2
  BENCH_OR_FAR = 3

  __slots__ = ['enableDilemma','dilemmaType','setDilemmaTime']
  _slot_types = ['bool','uint8','time']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       enableDilemma,dilemmaType,setDilemmaTime

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(dilemma, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.enableDilemma is None:
        self.enableDilemma = False
      if self.dilemmaType is None:
        self.dilemmaType = 0
      if self.setDilemmaTime is None:
        self.setDilemmaTime = genpy.Time()
    else:
      self.enableDilemma = False
      self.dilemmaType = 0
      self.setDilemmaTime = genpy.Time()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2B2I().pack(_x.enableDilemma, _x.dilemmaType, _x.setDilemmaTime.secs, _x.setDilemmaTime.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.setDilemmaTime is None:
        self.setDilemmaTime = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 10
      (_x.enableDilemma, _x.dilemmaType, _x.setDilemmaTime.secs, _x.setDilemmaTime.nsecs,) = _get_struct_2B2I().unpack(str[start:end])
      self.enableDilemma = bool(self.enableDilemma)
      self.setDilemmaTime.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2B2I().pack(_x.enableDilemma, _x.dilemmaType, _x.setDilemmaTime.secs, _x.setDilemmaTime.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.setDilemmaTime is None:
        self.setDilemmaTime = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 10
      (_x.enableDilemma, _x.dilemmaType, _x.setDilemmaTime.secs, _x.setDilemmaTime.nsecs,) = _get_struct_2B2I().unpack(str[start:end])
      self.enableDilemma = bool(self.enableDilemma)
      self.setDilemmaTime.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B2I = None
def _get_struct_2B2I():
    global _struct_2B2I
    if _struct_2B2I is None:
        _struct_2B2I = struct.Struct("<2B2I")
    return _struct_2B2I
